// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
  name, balance
) VALUES (
  $1, $2
)
RETURNING custid, name, balance, created_at
`

type CreateAccountParams struct {
	Name    string
	Balance pgtype.Numeric
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Balance)
	var i Account
	err := row.Scan(
		&i.Custid,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
