// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	Custid    int64
	Name      string
	Balance   pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID int64
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type Transaction struct {
	ID        int64
	FromID    int64
	ToID      int64
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
